name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read the value of the cmake version        
        run: |
          echo "cmakeVersion=$(grep cmakeVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the grpc version        
        run: |
          echo "grpcVersion=$(grep grpcVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the libwebsocketsVersion version        
        run: |
          echo "libwebsocketsVersion=$(grep libwebsocketsVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the speech SDK version
        run: |
          echo "speechSdkVersion=$(grep speechSdkVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the spandsp version
        run: |
          echo "spandspVersion=$(grep spandspVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT    
        shell: bash
      - name: Read the value of the sofia version
        run: |
          echo "sofiaVersion=$(grep sofiaVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the aws SDK CPP version
        run: |
          echo "awsSdkCppVersion=$(grep awsSdkCppVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash      
      - name: Read the value of the freeswitch modules version
        run: |
          echo "freeswitchModulesVersion=$(grep freeswitchModulesVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Read the value of the freeswitch version
        run: |
          echo "freeswitchVersion=$(grep freeswitchVersion $(Build.Repository.LocalPath)/.env | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash

      - name: prepare tag 
        id: prepare_tag
        run: |
            IMAGE_ID=drachtio/drachtio-freeswitch-mrf

            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

            # Strip "v" prefix from tag name
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

            # Use Docker `latest` tag convention
            [ "$VERSION" == "main" ] && VERSION=latest

            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION

            echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "drachtio/freeswitch-builder"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.prepare_tag.outputs.image_id }}:${{ steps.prepare_tag.outputs.version }}
          build-args: BUILD_CPUS=16,CMAKE_VERSION=${{ steps.prepare_tag.outputs.cmakeVersion }},GRPC_VERSION=${{ steps.prepare_tag.outputs.grpcVersion }},LIBWEBSOCKETS_VERSION=${{ steps.prepare_tag.outputs.libwebsocketsVersion }},SPEECH_SDK_VERSION=${{ steps.prepare_tag.outputs.speechSdkVersion }},SPANDSP_VERSION=${{ steps.prepare_tag.outputs.spandspVersion }},SOFIA_VERSION=${{ steps.prepare_tag.outputs.sofiaVersion }},AWS_SDK_CPP_VERSION=${{ steps.prepare_tag.outputs.awsSdkCppVersion }},FREESWITCH_MODULES_VERSION=${{ steps.prepare_tag.outputs.freeswitchModulesVersion }},FREESWITCH_VERSION=${{ steps.prepare_tag.outputs.freeswitchVersion }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
